server:
  port: 8761
logging:
  file: /java/C2S_LOGS/discovery-server/discovery-server.log
info:
  component: Discovery Server
eureka:
  instance:
   hostname: localhost
   non-secure-port: ${server.port}
   securePort: ${server.port}
   securePortEnabled: false
   nonSecurePortEnabled: true

  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    # Set this only for this sample service without which starting the instance will by default wait for the default of 5 mins
    waitTimeInMsWhenSyncEmpty: 0
    # Disable self-preservation during development, see https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication
    enable-self-preservation: false
    # for the example, set this to zero as we will not have peers to sync up with.
    # Do not set in a real environment with multi-node eureka clusters.
    numberRegistrySyncRetries: 0

---
spring.profiles: ssl
server:
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
   securePortEnabled: true
   nonSecurePortEnabled: false
---
spring.profiles: docker
eureka:
  instance:
    prefer-ip-address: true